### PR TITLE
Add installation info to README

### PR DESCRIPTION
**Pull request by void4**
This makes it a bit easier for new users to start. There's no link to the installation docs in the Wiki currently.

### CODE REVIEW

**Comment by pepijndevos** [comment]
I'd like to not direct people to the savinronja repo, as it is not maintained at all.

**Comment by void4** [comment]
I added all the info from the Wiki to the README
The installation info should be instantly accessible

**Comment by pepijndevos** [comment]
Sweet. Thanks. The zip file still links to savinronja though.

**Comment by void4** [comment]
Oops, fixed!

**Pull request merged**
