### PR TITLE
Fixed mac special keys

### PR DESCRIPTION
**Pull request by bruferrari**
Hey man, first of all, good work here! This lib has helped me a lot until now. I've noticed some bugs in mac.py, so I just fixed some things, two little things in fact, an event-type from NSEvent as global variable and wrong Quartz call in the end of press_special_key function, this one I believe that was put in there by mistake. Tested on Python 2.7.11

### CODE REVIEW

**Comment by pepijndevos** [comment]
Wait, how did this code work before? It seems NSSystemDefined was never defined anywhere. Is it necessary to define it though, or could it also be imported from Quartz/AppKit?

What version of OS X and PyObjC are you on? It would not be the first time that an API incompatibility sneaked in. I'd just like to make sure this does not break older versions of PyObjC.

**Comment by bruferrari** [comment]
Ok, well, I really don't know if this code has worked in mac before the perfomance improvements on Quartz imports, it's was the only one commit that I've checked, but that global var isn't defined there too. All the stuff is working very well except special keys, when press_special_key func is called NSSystemDefined isn't defined, so it breaks the code in runtime. If you take a look at stackoverflow thread link commented above function [http://stackoverflow.com/questions/11045814/emulate-media-key-press-on-mac](url) you will see that variable "NSSystemDefined = 14" as a global variable, I believe there's some way to get these events variables directly from Quartz/AppKit, but I don't know how, I'm trying to figure out.

If you want to take a look here [https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/occ/clm/NSEvent/otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:](url) I believe it was exactly what you have in your code and by clicking on NSEventType link [https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/doc/c_ref/NSEventType](url) you will see the list of these constants.

Currently I'm on PyObjC 3.1.1 on OSX 10.11.4, I don't know if these changes will break something in older versions of PyObjC or OSX, but it working for me, and it did not seems to work for special keys anyway independently of versions stuff and things like that.

If you could test the code yourself and make your own tests I'll be more safe too. If there's something more that I can do to help or test, please let me know.

**Comment by pepijndevos** [comment]
I don't have access to my Mac for the coming days. But from some googling it appears the constant should be a top level variable in Quartz or at least Cocoa, judging by this example: https://pythonhosted.org/pyobjc/examples/Cocoa/AppKit/HotKeyPython/index.html As you said, the import change probably broke it.

If you can use the PyObjC variable instead of your own and verify that works, I'd be happy to merge it. (and add you to the organisation)

**Comment by bruferrari** [comment]
You're right! I've imported NSSystemDefined from AppKit and it worked perfectly, even getting the variable from Cocoa, but in order to avoid another import and keep a cleaner code I'll get it from AppKit.

I'll send the corrections right now.

**Pull request merged**
