### PR TITLE
Updated mac.py to be more simiar to windows.py

### PR DESCRIPTION
**Pull request by SalvatoreTosti**
*Added diagnostic functionality to PyKeyboardEvent.
*Added stop function to mirror windows.py.
*Updated escape functionality to handler function.
*Added key_code_translate_table for value to key string lookup.

### CODE REVIEW

**Comment by pepijndevos** [comment]
I'm a bit hazy on the purpose on Windows of the lookup table. I vaguely remember some discussion about keyboard layouts. But Mac has universal keycodes, so that should not be an issue, I think?

Where did you get the values for the table from? It would be nice if the source was listed just as character_translate_table and special_key_translate_table.

Even nicer would be to get these values from PyObjC directly, but I'm not sure that's possible.

**Comment by pepijndevos** [comment]
Actually, it seems to be just the inverse of the other table? And only used in the diagnostics. So why not simply do something like

```python
res = dict((v,k) for k,v in a.iteritems())
```

**Comment by SalvatoreTosti** [comment]
key_code_translate_table is now generated programmatically, as described by @pepijndevos.

**Comment by pepijndevos** [comment]
Thanks. I invited you to the organization as well.

**Pull request merged**
